In [22]:
import pandas as pd


# ==========================================
# 1. Read Sofia's final dataset
# ==========================================

df = pd.read_csv("final_data_with_prompts.csv")

print("Original dataset size:", len(df))


# ==========================================
# 2. Remove unnecessary Unnamed column
# ==========================================

df = df.loc[:, ~df.columns.str.contains("^Unnamed")]


# ==========================================
# 3. Select Male patients
# ==========================================
# Conditions:
# Gender = Male
# Age = [40-50)
# Race = AfricanAmerican or Caucasian
# Pain levels = 0, 2, 4, 6, 8

male_selected = df[
    (df["gender"] == "Male") &
    (df["age"] == "[40-50)") &
    (df["race"].isin([
        "AfricanAmerican",
        "Caucasian"
    ])) &
    (df["pain_level"].isin([
        0, 2, 4, 6, 8
    ]))
].copy()


print("\nAvailable patients after filtering:")
print(
    pd.crosstab(
        male_selected["pain_level"],
        male_selected["race"]
    )
)


# ==========================================
# 4. Randomly select 5 patients
#    from each Pain Level × Race group
# ==========================================

male50 = (
    male_selected
    .groupby(
        ["pain_level", "race"],
        group_keys=False
    )
    .sample(
        n=5,
        random_state=42
    )
    .sort_values(
        ["pain_level", "race"]
    )
    .reset_index(drop=True)
)


# ==========================================
# 5. Keep only necessary columns
# ==========================================

male50 = male50[
    [
        "race",
        "gender",
        "age",
        "pain_level",
        "prompt"
    ]
]


# ==========================================
# 6. Check the selected data
# ==========================================

print("\nTotal selected:", len(male50))

print("\nPain level × Race:")
print(
    pd.crosstab(
        male50["pain_level"],
        male50["race"]
    )
)

print("\nGender:")
print(
    male50["gender"].value_counts()
)

print("\nAge:")
print(
    male50["age"].value_counts()
)


# ==========================================
# 7. Save male 50 prompts
# ==========================================

male50.to_csv(
    "male_50_prompts.csv",
    index=False
)

print("\nSaved successfully!")
print("File: male_50_prompts.csv")


# ==========================================
# 8. Display final dataset
# ==========================================

male50

Original dataset size: 98053

Available patients after filtering:
race        AfricanAmerican  Caucasian
pain_level
0                       156        319
2                       268        700
4                       126        318
6                        48        157
8                        14         39

Total selected: 50

Pain level × Race:
race        AfricanAmerican  Caucasian
pain_level
0                         5          5
2                         5          5
4                         5          5
6                         5          5
8                         5          5

Gender:
Male    50
Name: gender, dtype: int64

Age:
[40-50)    50
Name: age, dtype: int64

Saved successfully!
File: male_50_prompts.csv

,race,gender,age,pain_level,prompt
0,AfricanAmerican,Male,[40-50),0,I am a AfricanAmerican Male patient that is [4...
1,AfricanAmerican,Male,[40-50),0,I am a AfricanAmerican Male patient that is [4...
2,AfricanAmerican,Male,[40-50),0,I am a AfricanAmerican Male patient that is [4...
3,AfricanAmerican,Male,[40-50),0,I am a AfricanAmerican Male patient that is [4...
4,AfricanAmerican,Male,[40-50),0,I am a AfricanAmerican Male patient that is [4...
5,Caucasian,Male,[40-50),0,I am a Caucasian Male patient that is [40-50) ...
6,Caucasian,Male,[40-50),0,I am a Caucasian Male patient that is [40-50) ...
7,Caucasian,Male,[40-50),0,I am a Caucasian Male patient that is [40-50) ...
8,Caucasian,Male,[40-50),0,I am a Caucasian Male patient that is [40-50) ...
9,Caucasian,Male,[40-50),0,I am a Caucasian Male patient that is [40-50) ...
10,AfricanAmerican,Male,[40-50),2,I am a AfricanAmerican Male patient that is [4...
11,AfricanAmerican,Male,[40-50),2,I am a AfricanAmerican Male patient that is [4...
12,AfricanAmerican,Male,[40-50),2,I am a AfricanAmerican Male patient that is [4...
13,AfricanAmerican,Male,[40-50),2,I am a AfricanAmerican Male patient that is [4...
14,AfricanAmerican,Male,[40-50),2,I am a AfricanAmerican Male patient that is [4...
15,Caucasian,Male,[40-50),2,I am a Caucasian Male patient that is [40-50) ...
16,Caucasian,Male,[40-50),2,I am a Caucasian Male patient that is [40-50) ...
17,Caucasian,Male,[40-50),2,I am a Caucasian Male patient that is [40-50) ...
18,Caucasian,Male,[40-50),2,I am a Caucasian Male patient that is [40-50) ...
19,Caucasian,Male,[40-50),2,I am a Caucasian Male patient that is [40-50) ...
20,AfricanAmerican,Male,[40-50),4,I am a AfricanAmerican Male patient that is [4...
21,AfricanAmerican,Male,[40-50),4,I am a AfricanAmerican Male patient that is [4...
22,AfricanAmerican,Male,[40-50),4,I am a AfricanAmerican Male patient that is [4...
23,AfricanAmerican,Male,[40-50),4,I am a AfricanAmerican Male patient that is [4...
24,AfricanAmerican,Male,[40-50),4,I am a AfricanAmerican Male patient that is [4...
25,Caucasian,Male,[40-50),4,I am a Caucasian Male patient that is [40-50) ...
26,Caucasian,Male,[40-50),4,I am a Caucasian Male patient that is [40-50) ...
27,Caucasian,Male,[40-50),4,I am a Caucasian Male patient that is [40-50) ...
28,Caucasian,Male,[40-50),4,I am a Caucasian Male patient that is [40-50) ...
29,Caucasian,Male,[40-50),4,I am a Caucasian Male patient that is [40-50) ...
30,AfricanAmerican,Male,[40-50),6,I am a AfricanAmerican Male patient that is [4...
31,AfricanAmerican,Male,[40-50),6,I am a AfricanAmerican Male patient that is [4...
32,AfricanAmerican,Male,[40-50),6,I am a AfricanAmerican Male patient that is [4...
33,AfricanAmerican,Male,[40-50),6,I am a AfricanAmerican Male patient that is [4...
34,AfricanAmerican,Male,[40-50),6,I am a AfricanAmerican Male patient that is [4...
35,Caucasian,Male,[40-50),6,I am a Caucasian Male patient that is [40-50) ...
36,Caucasian,Male,[40-50),6,I am a Caucasian Male patient that is [40-50) ...
37,Caucasian,Male,[40-50),6,I am a Caucasian Male patient that is [40-50) ...
38,Caucasian,Male,[40-50),6,I am a Caucasian Male patient that is [40-50) ...
39,Caucasian,Male,[40-50),6,I am a Caucasian Male patient that is [40-50) ...
40,AfricanAmerican,Male,[40-50),8,I am a AfricanAmerican Male patient that is [4...
41,AfricanAmerican,Male,[40-50),8,I am a AfricanAmerican Male patient that is [4...
42,AfricanAmerican,Male,[40-50),8,I am a AfricanAmerican Male patient that is [4...
43,AfricanAmerican,Male,[40-50),8,I am a AfricanAmerican Male patient that is [4...
44,AfricanAmerican,Male,[40-50),8,I am a AfricanAmerican Male patient that is [4...
45,Caucasian,Male,[40-50),8,I am a Caucasian Male patient that is [40-50) ...
46,Caucasian,Male,[40-50),8,I am a Caucasian Male patient that is [40-50) ...
47,Caucasian,Male,[40-50),8,I am a Caucasian Male patient that is [40-50) ...
48,Caucasian,Male,[40-50),8,I am a Caucasian Male patient that is [40-50) ...
49,Caucasian,Male,[40-50),8,I am a Caucasian Male patient that is [40-50) ...

In [23]:
# ==========================================
# Select 50 Female patients
# ==========================================

female_selected = df[
    (df["gender"] == "Female") &
    (df["age"] == "[40-50)") &
    (df["race"].isin(["AfricanAmerican", "Caucasian"])) &
    (df["pain_level"].isin([0, 2, 4, 6, 8]))
]


# 5 patients for each Pain Level × Race combination
female50 = (
    female_selected
    .groupby(["pain_level", "race"])
    .sample(n=5, random_state=42)
    .sort_values(["pain_level", "race"])
    .reset_index(drop=True)
)


# Keep the columns we need
female50 = female50[
    [
        "race",
        "gender",
        "age",
        "pain_level",
        "prompt"
    ]
]


# Save the 50 prompts
female50.to_csv(
    "female_50_prompts.csv",
    index=False
)


# Check the result
print("Total:", len(female50))

print("\nPain level × Race:")
print(
    pd.crosstab(
        female50["pain_level"],
        female50["race"]
    )
)

female50

Total: 50

Pain level × Race:
race        AfricanAmerican  Caucasian
pain_level
0                         5          5
2                         5          5
4                         5          5
6                         5          5
8                         5          5

,race,gender,age,pain_level,prompt
0,AfricanAmerican,Female,[40-50),0,I am a AfricanAmerican Female patient that is ...
1,AfricanAmerican,Female,[40-50),0,I am a AfricanAmerican Female patient that is ...
2,AfricanAmerican,Female,[40-50),0,I am a AfricanAmerican Female patient that is ...
3,AfricanAmerican,Female,[40-50),0,I am a AfricanAmerican Female patient that is ...
4,AfricanAmerican,Female,[40-50),0,I am a AfricanAmerican Female patient that is ...
5,Caucasian,Female,[40-50),0,I am a Caucasian Female patient that is [40-50...
6,Caucasian,Female,[40-50),0,I am a Caucasian Female patient that is [40-50...
7,Caucasian,Female,[40-50),0,I am a Caucasian Female patient that is [40-50...
8,Caucasian,Female,[40-50),0,I am a Caucasian Female patient that is [40-50...
9,Caucasian,Female,[40-50),0,I am a Caucasian Female patient that is [40-50...
10,AfricanAmerican,Female,[40-50),2,I am a AfricanAmerican Female patient that is ...
11,AfricanAmerican,Female,[40-50),2,I am a AfricanAmerican Female patient that is ...
12,AfricanAmerican,Female,[40-50),2,I am a AfricanAmerican Female patient that is ...
13,AfricanAmerican,Female,[40-50),2,I am a AfricanAmerican Female patient that is ...
14,AfricanAmerican,Female,[40-50),2,I am a AfricanAmerican Female patient that is ...
15,Caucasian,Female,[40-50),2,I am a Caucasian Female patient that is [40-50...
16,Caucasian,Female,[40-50),2,I am a Caucasian Female patient that is [40-50...
17,Caucasian,Female,[40-50),2,I am a Caucasian Female patient that is [40-50...
18,Caucasian,Female,[40-50),2,I am a Caucasian Female patient that is [40-50...
19,Caucasian,Female,[40-50),2,I am a Caucasian Female patient that is [40-50...
20,AfricanAmerican,Female,[40-50),4,I am a AfricanAmerican Female patient that is ...
21,AfricanAmerican,Female,[40-50),4,I am a AfricanAmerican Female patient that is ...
22,AfricanAmerican,Female,[40-50),4,I am a AfricanAmerican Female patient that is ...
23,AfricanAmerican,Female,[40-50),4,I am a AfricanAmerican Female patient that is ...
24,AfricanAmerican,Female,[40-50),4,I am a AfricanAmerican Female patient that is ...
25,Caucasian,Female,[40-50),4,I am a Caucasian Female patient that is [40-50...
26,Caucasian,Female,[40-50),4,I am a Caucasian Female patient that is [40-50...
27,Caucasian,Female,[40-50),4,I am a Caucasian Female patient that is [40-50...
28,Caucasian,Female,[40-50),4,I am a Caucasian Female patient that is [40-50...
29,Caucasian,Female,[40-50),4,I am a Caucasian Female patient that is [40-50...
30,AfricanAmerican,Female,[40-50),6,I am a AfricanAmerican Female patient that is ...
31,AfricanAmerican,Female,[40-50),6,I am a AfricanAmerican Female patient that is ...
32,AfricanAmerican,Female,[40-50),6,I am a AfricanAmerican Female patient that is ...
33,AfricanAmerican,Female,[40-50),6,I am a AfricanAmerican Female patient that is ...
34,AfricanAmerican,Female,[40-50),6,I am a AfricanAmerican Female patient that is ...
35,Caucasian,Female,[40-50),6,I am a Caucasian Female patient that is [40-50...
36,Caucasian,Female,[40-50),6,I am a Caucasian Female patient that is [40-50...
37,Caucasian,Female,[40-50),6,I am a Caucasian Female patient that is [40-50...
38,Caucasian,Female,[40-50),6,I am a Caucasian Female patient that is [40-50...
39,Caucasian,Female,[40-50),6,I am a Caucasian Female patient that is [40-50...
40,AfricanAmerican,Female,[40-50),8,I am a AfricanAmerican Female patient that is ...
41,AfricanAmerican,Female,[40-50),8,I am a AfricanAmerican Female patient that is ...
42,AfricanAmerican,Female,[40-50),8,I am a AfricanAmerican Female patient that is ...
43,AfricanAmerican,Female,[40-50),8,I am a AfricanAmerican Female patient that is ...
44,AfricanAmerican,Female,[40-50),8,I am a AfricanAmerican Female patient that is ...
45,Caucasian,Female,[40-50),8,I am a Caucasian Female patient that is [40-50...
46,Caucasian,Female,[40-50),8,I am a Caucasian Female patient that is [40-50...
47,Caucasian,Female,[40-50),8,I am a Caucasian Female patient that is [40-50...
48,Caucasian,Female,[40-50),8,I am a Caucasian Female patient that is [40-50...
49,Caucasian,Female,[40-50),8,I am a Caucasian Female patient that is [40-50...